[package]
name = "dpEditor"
version = "0.1.0"
edition = "2024"

[dependencies]
# Основная графика
druid = "0.8.3"
wgpu = "25.0.0"

# Прочее
rand = "0.9.0"
serde = "1.0.219"
serde_json = "1.0.140"
nalgebra = "0.33.2"

# Звук
rodio = "0.20.1"
