[package]
name = "dpEditor"
version = "0.1.0"
edition = "2024"

[dependencies]
# Основная графика
eframe = "0.31.1"
egui = "0.31.1"
macroquad = "0.4.14"

# Прочее
glam = "0.30.1"
rand = "=0.3.14"
serde = "1.0.219"
serde_json = "1.0.140"

# Звук
rodio = "0.20.1"
